const COMPANIES = [
  { name: "Razorpay",        ats: "greenhouse", slug: "razorpay" },
  { name: "PhonePe",         ats: "greenhouse", slug: "phonepe" },
  { name: "Meesho",          ats: "greenhouse", slug: "meesho" },
  { name: "CRED",            ats: "greenhouse", slug: "cred" },
  { name: "Freshworks",      ats: "greenhouse", slug: "freshworks" },
  { name: "Browserstack",    ats: "greenhouse", slug: "browserstack" },
  { name: "Postman",         ats: "greenhouse", slug: "postman" },
  { name: "Chargebee",       ats: "greenhouse", slug: "chargebee" },
  { name: "Hasura",          ats: "greenhouse", slug: "hasura" },
  { name: "Clevertap",       ats: "greenhouse", slug: "clevertap" },
  { name: "InMobi",          ats: "greenhouse", slug: "inmobi" },
  { name: "Druva",           ats: "greenhouse", slug: "druva" },
  { name: "Darwinbox",       ats: "greenhouse", slug: "darwinbox" },
  { name: "Innovaccer",      ats: "greenhouse", slug: "innovaccer" },
  { name: "Licious",         ats: "greenhouse", slug: "licious" },
  { name: "Urban Company",   ats: "greenhouse", slug: "urbancompany" },
  { name: "Moglix",          ats: "greenhouse", slug: "moglix" },
  { name: "Spinny",          ats: "greenhouse", slug: "spinny" },
  { name: "Slice",           ats: "greenhouse", slug: "slice" },
  { name: "Khatabook",       ats: "greenhouse", slug: "khatabook" },
  { name: "Flipkart",        ats: "lever", slug: "flipkart" },
  { name: "Swiggy",          ats: "lever", slug: "swiggy" },
  { name: "Zomato",          ats: "lever", slug: "zomato" },
  { name: "Ola",             ats: "lever", slug: "ola-cabs" },
  { name: "ShareChat",       ats: "lever", slug: "sharechat" },
  { name: "Delhivery",       ats: "lever", slug: "delhivery" },
  { name: "Cashfree",        ats: "lever", slug: "cashfree" },
  { name: "Infosys",         ats: "workday", tenant: "infosys" },
  { name: "Wipro",           ats: "workday", tenant: "wipro" },
  { name: "Cognizant",       ats: "workday", tenant: "cognizant" },
];

module.exports = { COMPANIES };
